### ISSUE TITLE
Settings manager won't save settings such as mouse acceleration

### ISSUE THREAD

**Issue by yikaizhou252** [Syndrizzle/hotfiles#43]
It's a lovely setup btw and I'm very new to ricing so I apologize in advance for my newbie issues.

The settings for mouse acceleration and display scaling that I configured in the settings manager won't apply even after a reboot and I'm not sure why. Thanks in advance.

**Comment by Syndrizzle** [comment]
Settings Manager mostly works for Xfce session, you can only change a few things in it since we are not using xfce4 session, for display scaling you can edit the DPi in `~/.Xresources`, by changing it from 120 to any other DPi
For mouse acceleration, [You can check this ArchWiki guide on how to do it with libinput](https://wiki.archlinux.org/title/Mouse_acceleration#Mouse_acceleration_with_libinput)
I hope that helps :)

**Comment by yikaizhou252** [comment]
Makes sense, I added Xft.dpi value in the Xresources file and that solved the issue. Thanks man
